Sprint 2/step 2
maslovich1985/react-burger pull request #3
Opened 2023-02-26 22:20 UTC by maslovich1985

2023-02-27 05:31 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/ziow95nrzzGs6Q> - Текст тоже должен быть белого цвета;

- Исправить ошибку в консоли: <https://disk.yandex.com/i/IaS5RkIeSQOEig>;

- У вас возникают ошибки в консоли, если перетащить ингредиент: <https://disk.yandex.com/i/2VonLBX_PTAaZw>;

- Нужно запретить нажатие кнопки `Отправить`, если пользователь выбрал только ингредиенты <https://disk.yandex.com/i/F-kJ9SxQRr95ig>, и также нужно подправить вёрстку ингредиента;

- Папку `services` нужно переместить в `src`.

### **Сделает код лучше:**

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. <https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-27 05:31 UTC, ArslanDev666 commented on src/utils/services/redux/reducers/viewedIngredientReducer.js
> +    ingredientDetails: {}
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-02-27 05:31 UTC, ArslanDev666 commented on src/utils/services/redux/reducers/orderReducer.js
> +    order: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-02-27 05:31 UTC, ArslanDev666 commented on src/utils/services/redux/reducers/ingredientsListReducer.js
> +            return {...state, ingredients: increaseCounter };
**Можно лучше:**

Кажется, вы тут очень намудрили, всё гораздо прощё: 

```js
const { id: increasedId } = action.payload;

const updateIngredients = state.ingredients.map((item) => {
    if(item._id !== increasedId) return item;

    item.count = item.type === 'bun' ? 2 : item.count + 1

    return item;
}); 
return { ...state, ingredients: updateIngredients };
```

2023-02-27 05:31 UTC, ArslanDev666 commented on src/utils/services/redux/reducers/burgerIngredientsReducer.js
> +
**Можно лучше:**

Тут можно разделить стейт на `bun` и `ingredients`. Тогда думаю эту логику можно написать в разы проще. А так, попробуйте метод `reduce` тут применить.

2023-02-27 05:31 UTC, ArslanDev666 commented on src/utils/services/redux/actions/viewedIngredientActions.js
> +    const data = store.getState().ingredients.ingredients;
**Рекомендую исправить:**

Не очень хорошая практика использовать тут store.getState(), в этом случае лучше искать нужный ингредиент прямо в редьюсере.

2023-02-27 05:31 UTC, ArslanDev666 commented on src/utils/services/redux/actions/burgerIngredientsActions.js
> +    const data = store.getState().ingredients.ingredients;
**Рекомендую исправить:**

Аналогичное замечания в `viewedIngredientActions`.

2023-02-27 05:31 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    }, [])
**Надо исправить:**

закрытие попапа по ESC относится к функционалу модального окна и должно быть описано в компоненте Modal.

2023-02-27 05:31 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerIngredients/BurgerIngredients.jsx
> +            </div>}
**Можно лучше:**

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: burgerData.find(item => item.type === 'bun'),
    ingredients: burgerData.filter(item => item.type !== 'bun'),
  };
}, [burgerData]);
```

2023-02-27 22:04 UTC, maslovich1985 commented on src/utils/services/redux/reducers/viewedIngredientReducer.js
> +    ingredientDetails: {}
Исправил

2023-02-27 22:04 UTC, maslovich1985 commented on src/utils/services/redux/reducers/orderReducer.js
> +    order: {},
Исправил

2023-02-27 22:07 UTC, maslovich1985 commented on src/utils/services/redux/reducers/ingredientsListReducer.js
> +            return {...state, ingredients: increaseCounter };
Не работает в случае, когда нужно менять булку на булку, для этого один счетчик обнуляем, второму прибавляем +2

2023-02-27 22:07 UTC, maslovich1985 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    }, [])
Исправил

2023-02-27 22:08 UTC, maslovich1985 commented on src/components/BurgerConstructor/BurgerIngredients/BurgerIngredients.jsx
> +            </div>}
Исправил

2023-02-28 05:03 UTC, ArslanDev666 commented on src/utils/services/redux/reducers/ingredientsListReducer.js
> +            return {...state, ingredients: increaseCounter };
Действительно, что-то очень простой случай взял)) в таком случае, можно вообще выпилить это поле)) и сделать этот функционал в `ingredients-type`;

```jsx
const ingredientsCounters = useMemo(() => {
  const { bun, ingredients } = burgerConstructor;
  const counters = {};
  ingredients.forEach((ingredient) => {
    if (!counters[ingredient._id]) counters[ingredient._id] = 0;
    counters[ingredient._id]++;
  });
  if (bun) counters[bun._id] = 2;
  return counters;
}, [burgerConstructor]);

//...
{ingredients.map((ingredient) => {
  return (
    <BurgerIngredient
      ingredientData={ingredient}
      key={ingredient._id}
      count={ingredientsCounters[ingredient._id]}
      onClick={onIngredientClick}
    />
  );
})}
```
Это просто удачный пример)) вам скорее всего придётся чуток под себя его подгонять.

2023-02-28 05:07 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-03-24 18:16 UTC, merged