Sprint 3/step 1
maslovich1985/react-burger pull request #4
Opened 2023-03-20 23:31 UTC by maslovich1985

2023-03-21 03:44 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/zCzv6ofw5MppUQ> - кажется, вы забыли иконку включить);

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- <https://disk.yandex.com/i/zhGp1k6anb943Q> - модальное окно должно закрываться по клику на overlay, а у вас этого не происходит;

- По чек-листу, требуется реализовать:

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;

  - `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;

  - При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым;

  - Роуты `/profile` и все вложенные в `/profile` маршруты доступны только авторизованным пользователям, т. е. защищены HOC-компонентом ProtectedRoute.

  - При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на `/login`. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее.

Перед отправкой работы, проверьте чтобы пользователю (который уже залогинен), не пришлось, при перезагрузки страницы, снова проходить авторизацию.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-21 03:44 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +                        <ProtectedRouteElement>
**Можно лучше:**

не совсем понимаю, зачем оборачивать этот компонент в `protectRoute`

2023-03-21 03:44 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerIngredients/BurgerIngredients.jsx
> +            bun: data.filter(item => item.type === 'bun'),
**Можно лучше:**

тут лучше использовать метод `find`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2023-03-21 03:44 UTC, ArslanDev666 commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +}
**Можно лучше:**

попробуй улучшить компонент. Сейчас вы не дожидаетесь запроса сервера для получения данных о пользователе, а просто проверяете авторизирован пользователь или нет, а это может привести к багу: когда пользователь залогинен, он перезагрузит страницу, и ему снова придётся логинтся, ибо запрос не успеет проверить токен.

вот хороший пример компонента, попробуйте его переделать под себя.

```jsx
const ProtectedRoute = ({ onlyUnAuth = false, ...rest }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Redirect to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Redirect
        to={{
          pathname: "/login",
          state: { from: location },
        }}
      />
    );
  }

  return <Route {...rest} />;
};
```

2023-03-21 03:44 UTC, ArslanDev666 commented on src/pages/ForgotPassword/ForgotPassword.jsx
> +    const [email, setEmail] = useState('');
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-03-21 03:44 UTC, ArslanDev666 commented on src/utils/burger-api.js
> +export function getOrder(orderData) {
**Надо исправить:**

При получении и обновлении информации о пользователе серверу передаётся токен  в поле authorization. Тут также нужен передавать токен.

2023-03-21 03:44 UTC, ArslanDev666 commented on src/services/redux/actions/userActions.js
> +            if (e.message === 'jwt expired') {
**Можно лучше:**

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-03-21 22:16 UTC, maslovich1985 commented on src/utils/burger-api.js
> +export function getOrder(orderData) {
Исправил

2023-03-21 22:16 UTC, maslovich1985 commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +}
Улучшил

2023-03-21 22:17 UTC, maslovich1985 commented on src/components/App/App.jsx
> +                        <ProtectedRouteElement>
Убрал

2023-03-21 22:20 UTC, maslovich1985 commented
> ## Code Review
> Здравствуйте!
> 
> Отличная работа.
> 
> ### **Вы молодец!**
> * Сборка и запуск проекта выполняются без ошибок;
> * Теперь у вас есть роутинг;
> * Есть регистрация и авторизация;
> 
> ### **Но есть несколько замечаний, которые нужно исправить:**
> * https://disk.yandex.com/i/zCzv6ofw5MppUQ - кажется, вы забыли иконку включить);
> * Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);
> * https://disk.yandex.com/i/zhGp1k6anb943Q - модальное окно должно закрываться по клику на overlay, а у вас этого не происходит;
> * По чек-листу, требуется реализовать:
>   
>   * Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;
>   * `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;
>   * При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым;
>   * Роуты `/profile` и все вложенные в `/profile` маршруты доступны только авторизованным пользователям, т. е. защищены HOC-компонентом ProtectedRoute.
>   * При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на `/login`. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее.
> 
> Перед отправкой работы, проверьте чтобы пользователю (который уже залогинен), не пришлось, при перезагрузки страницы, снова проходить авторизацию.
> 
> ### **Сделает код лучше:**
> * Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders
> 
> #### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**



> * При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым;

Замечания исправил кроме
```
 *  При клике на «История заказов» происходит переход на экран /profile/orders, ссылка «История заказов» становится активной, экран /profile/orders пока отображается пустым;
```

Этот сценарий в следующем спринте по плану

2023-03-22 00:37 UTC, ArslanDev666 commented
> > ## Code Review
> > Здравствуйте!
> > Отличная работа.
> > ### **Вы молодец!**
> > 
> > * Сборка и запуск проекта выполняются без ошибок;
> > * Теперь у вас есть роутинг;
> > * Есть регистрация и авторизация;
> > 
> > ### **Но есть несколько замечаний, которые нужно исправить:**
> > 
> > * https://disk.yandex.com/i/zCzv6ofw5MppUQ - кажется, вы забыли иконку включить);
> > * Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);
> > * https://disk.yandex.com/i/zhGp1k6anb943Q - модальное окно должно закрываться по клику на overlay, а у вас этого не происходит;
> > * По чек-листу, требуется реализовать:
> >   
> >   * Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;
> >   * `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;
> >   * При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым;
> >   * Роуты `/profile` и все вложенные в `/profile` маршруты доступны только авторизованным пользователям, т. е. защищены HOC-компонентом ProtectedRoute.
> >   * При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на `/login`. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее.
> > 
> > Перед отправкой работы, проверьте чтобы пользователю (который уже залогинен), не пришлось, при перезагрузки страницы, снова проходить авторизацию.
> > ### **Сделает код лучше:**
> > 
> > * Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders
> > 
> > #### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**
> 
> > * При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым;
> 
> Замечания исправил кроме
> 
> ```
>  *  При клике на «История заказов» происходит переход на экран /profile/orders, ссылка «История заказов» становится активной, экран /profile/orders пока отображается пустым;
> ```
> 
> Этот сценарий в следующем спринте по плану

Ну вообще, реализовывать данный сценарий нужно в этом спринте, если судить по чек-листу https://disk.yandex.com/i/1FXQpmiKYNtAqQ. Но это вроде не критично, поэтому, думаю можно оставить и на следующий спринт.

2023-03-22 00:42 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены;

### **Сделает код лучше:**

- <https://disk.yandex.com/i/zCzv6ofw5MppUQ> - кажется, вы забыли иконку включить);

2023-03-24 18:16 UTC, merged